server:
  port: 7000
spring:
  application:
    name: sust-swy-crowd-pay
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.40.128
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
ali:
  pay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmFz8V/HmdZtI6NyeXM35GmuL5UMFFek45mE8F9GEChAbExFcMOxepOursIHd7dGAJFR6HDXblPJHmAMCK2akWhxW7sNXhisIWXKp2gF9f3F0rVSn+ylvlot0gx6IbkZVB1rNnEEyub4+xinxuij5+tUu6wtyfWfzpEiu9keS0b4oFp2bldjct0VHWfGr0bUQR/lTbQcdENpjGEIj3N0aN98rpvD7mIf77Xy7JCMzE1W+JDqGyF5Vye4UYlweoI0S5ciIoq12XCgo3i/i6bMjDiVHDGDDeZUZGekVPGPbg2uPexroztonoNi52vuedl6mNhABmtBCrAIePOP3UL7D6wIDAQAB
    app-id: 2021000117646921
    charset: utf-8
    gateway-url: https://openapi.alipaydev.com/gateway.do
    merchant-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCLBKkxQBFnOms8uam4KP0IqqtfKX+EdVp7qIfjYTYBBAc/BWCkHiTSHBSwoBu54a2JLNQou0AF9DZ1zgKnem4zOvK8Ok6WxLLm50NmtNsDdAlaD3xdPI8Avhhj/qvZQrZAziBLNaMvrR/HLOALpaPyyqI+kxHhpwj3fmJ7xepI9EIV+24cKFppyugQj8Ug30JbThu7YEQOLujJ1DjUA2rR+7fWfQluiM2I9kADzKJv++6A2dsREza7kzJa2VN6fDDSjXqxlOcwpo2c7C6PGuUtUM38QbcjwFcDRbzqyfyVm/StpTxpCjDsirABtn6GK65UhGIxaiUuc5uZwAjJw8s7AgMBAAECggEANYU62iIvUQ21oXBdPfBR0ldamM1yMX24syjkAA856lQxsfqRBT4xsM5szL8nTX3sAIbIu1GzyVcG7H2+mdnRuVl1gC/2d6cMtUbNtSnls8Olog2aNI8PAxssarruUDuVzQdOeYYR6FX/iP/m1bUUlHGc2vhmBvj2w8ndgodktmb4kMTjBs4LGcCZXPRnPuZmZ8ZtuoKI3DKVhAxA7z0tcaJKFIvaSuedE1Nioy/JdzXYX8i/G66xB9J5FWdZHdSw6IbURWYlq0RSNB+wFSgZoBEUE6rmhry5zyYoNE9008as9tAvBu4BYSk+N5tgWVLibk2qjkYpRbX6LxkxwVAOYQKBgQDZ69jW7fm5PhWmcMeDAULSo6mxGKGPOKcPKNs+SqGsLSvX/OkytAE00XcsfQoW2vEmXuridZTkvat6TXNofktXaBeTc2qi59mu+vIIsFmDXoZD53oqXT+4ixSz7SggHXHvOPE/u599NYSpPCJVsw8UD5mlt5xsbo1zpS7JXNzfkQKBgQCjT0k9W9mGF6wX1hZcsYSJ9CqTRaaDk6geOzfa6nrzgfZcrk3uybBqRJNHH9o1turTRuKIbRYm0xAFU9GgDaJZDa+Yz10jq43Gh+cCkBHDSo7gw13AxLlphHqfTXyXt08t9GmTeEU6kSlcq+R/d22IFdErSzHRq4sLOGvxBSswCwKBgBvrByCh5DhDJ+rmz+iMpM7vgLHbgfcjPuPGTDAyx3uTXeaR1B5WyUDHBQmCC2TaL8LGrjjM74JOekV03rAoXeaYw0x0oNi180FjjNZoIU+fMHxKj3AV+i/eQYy7eUSEATCwjtenZctYq+IyfgOUqP3c8cY1O6j4kM6b/t51MybBAoGAbG5mWKE1qrzo/OKe8mjDcb12z1X9m3tcssXq7iWmASyXYS4yfIvZ4JUrnJvfjK6o+CMmoiKcBKc7Ce5/Tt/+nVZi8vksBFURy3HMxnzV7m8AsufExgtYeGEH8eHHCg0iO4b+2nWOsbZUWj2fd6raRPMHcNF6gJZ/ubF6qgseg8UCgYB4T1sBX9SvYBUL+E4IBklzM20U1Ru7LJdQxGvJiS4Kc+p1Z6HVhieKDk2NLvv6/GMEq3Xs28XbE3KnwsT0UAXOJNdbrR6A9DIm1WHkeNghrR9lToSdeGPbWfVVebOqB+r2IipQE3lU+vEqiw7d3YNVG4Zx/avIo7BPIYp/5Qn7eA==
    notify-url: http://vkagpt.natappfree.cc/pay/notify
    return-url: http://localhost/pay/return
    sign-type: RSA2