server: 
  port: 3000 
spring: 
  application: 
    name: sust-swy-crowd-redis
  redis:
    host: 192.168.1.21
    port: 6379
eureka: 
  instance: 
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka