package com.sust.swy.print.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sust.swy.print.entity.Document;
import com.sust.swy.print.entity.DocumentExample;

public interface DocumentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int countByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int deleteByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int insert(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int insertSelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    List<Document> selectByExample(DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    Document selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByExampleSelective(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByExample(@Param("record") Document record, @Param("example") DocumentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByPrimaryKeySelective(Document record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_document
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByPrimaryKey(Document record);
}