package com.sust.swy.print.mapper;

import com.sust.swy.print.entity.Machine;
import com.sust.swy.print.entity.MachineExample;
import com.sust.swy.print.entity.MachineWithMerchant;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int countByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int deleteByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int insert(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int insertSelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    List<Machine> selectByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    Machine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByExampleSelective(@Param("record") Machine record, @Param("example") MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByExample(@Param("record") Machine record, @Param("example") MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByPrimaryKeySelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_machine
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    int updateByPrimaryKey(Machine record);

	List<MachineWithMerchant> selectMachineByKeyword(@Param("keyword") String keyword);
}