package com.sust.swy.print.mapper;

import com.sust.swy.print.entity.Member;
import com.sust.swy.print.entity.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int countByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	Member selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table t_member
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	int updateByPrimaryKey(Member record);

	List<Member> selectMemberByKeyword(@Param("keyword") String keyword);
}