server: 
  port: 80
spring: 
  application: 
    name: sust-swy-crowd-zuul
  redis:
    host: 192.168.40.128
    jedis:
      pool:
        max-idle: 100
  session:
    store-type: redis
eureka: 
  instance: 
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:1000/eureka
zuul:  ignored-services: "*"
  sensitive-headers: "*"
  routes:    crowd-portal:
      service-id: sust-swy-crowd-auth
      path: /**
    crowd-project:
      service-id: sust-swy-crowd-project
      path: /project/**
      
      