package com.sust.swy.print.entity;

import java.util.Date;

public class Document {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.member_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.document_name
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String documentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.document_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer documentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.document_size
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String documentSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.document_url
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String documentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_document.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.id
     *
     * @return the value of t_document.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.id
     *
     * @param id the value for t_document.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.member_id
     *
     * @return the value of t_document.member_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.member_id
     *
     * @param memberId the value for t_document.member_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.document_name
     *
     * @return the value of t_document.document_name
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.document_name
     *
     * @param documentName the value for t_document.document_name
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName == null ? null : documentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.document_status
     *
     * @return the value of t_document.document_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getDocumentStatus() {
        return documentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.document_status
     *
     * @param documentStatus the value for t_document.document_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setDocumentStatus(Integer documentStatus) {
        this.documentStatus = documentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.document_size
     *
     * @return the value of t_document.document_size
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getDocumentSize() {
        return documentSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.document_size
     *
     * @param documentSize the value for t_document.document_size
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setDocumentSize(String documentSize) {
        this.documentSize = documentSize == null ? null : documentSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.document_url
     *
     * @return the value of t_document.document_url
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getDocumentUrl() {
        return documentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.document_url
     *
     * @param documentUrl the value for t_document.document_url
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setDocumentUrl(String documentUrl) {
        this.documentUrl = documentUrl == null ? null : documentUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.update_time
     *
     * @return the value of t_document.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.update_time
     *
     * @param updateTime the value for t_document.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_document.is_delete
     *
     * @return the value of t_document.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_document.is_delete
     *
     * @param isDelete the value for t_document.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}