package com.sust.swy.print.entity;

import java.util.Date;

public class Machine {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.id
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.merchant_id
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private Integer merchantId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.machine_name
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private String machineName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.machine_status
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private Integer machineStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.machine_type
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private Integer machineType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.update_time
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private Date updateTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t_machine.is_delete
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	private Integer isDelete;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.id
	 *
	 * @return the value of t_machine.id
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.id
	 *
	 * @param id the value for t_machine.id
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.merchant_id
	 *
	 * @return the value of t_machine.merchant_id
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public Integer getMerchantId() {
		return merchantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.merchant_id
	 *
	 * @param merchantId the value for t_machine.merchant_id
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.machine_name
	 *
	 * @return the value of t_machine.machine_name
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public String getMachineName() {
		return machineName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.machine_name
	 *
	 * @param machineName the value for t_machine.machine_name
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setMachineName(String machineName) {
		this.machineName = machineName == null ? null : machineName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.machine_status
	 *
	 * @return the value of t_machine.machine_status
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public Integer getMachineStatus() {
		return machineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.machine_status
	 *
	 * @param machineStatus the value for t_machine.machine_status
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setMachineStatus(Integer machineStatus) {
		this.machineStatus = machineStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.machine_type
	 *
	 * @return the value of t_machine.machine_type
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public Integer getMachineType() {
		return machineType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.machine_type
	 *
	 * @param machineType the value for t_machine.machine_type
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setMachineType(Integer machineType) {
		this.machineType = machineType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.update_time
	 *
	 * @return the value of t_machine.update_time
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.update_time
	 *
	 * @param updateTime the value for t_machine.update_time
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t_machine.is_delete
	 *
	 * @return the value of t_machine.is_delete
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public Integer getIsDelete() {
		return isDelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t_machine.is_delete
	 *
	 * @param isDelete the value for t_machine.is_delete
	 *
	 * @mbggenerated Tue May 18 09:20:06 CST 2021
	 */
	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}
}