package com.sust.swy.print.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MerchantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public MerchantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLoginAcctIsNull() {
            addCriterion("login_acct is null");
            return (Criteria) this;
        }

        public Criteria andLoginAcctIsNotNull() {
            addCriterion("login_acct is not null");
            return (Criteria) this;
        }

        public Criteria andLoginAcctEqualTo(String value) {
            addCriterion("login_acct =", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctNotEqualTo(String value) {
            addCriterion("login_acct <>", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctGreaterThan(String value) {
            addCriterion("login_acct >", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctGreaterThanOrEqualTo(String value) {
            addCriterion("login_acct >=", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctLessThan(String value) {
            addCriterion("login_acct <", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctLessThanOrEqualTo(String value) {
            addCriterion("login_acct <=", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctLike(String value) {
            addCriterion("login_acct like", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctNotLike(String value) {
            addCriterion("login_acct not like", value, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctIn(List<String> values) {
            addCriterion("login_acct in", values, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctNotIn(List<String> values) {
            addCriterion("login_acct not in", values, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctBetween(String value1, String value2) {
            addCriterion("login_acct between", value1, value2, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginAcctNotBetween(String value1, String value2) {
            addCriterion("login_acct not between", value1, value2, "loginAcct");
            return (Criteria) this;
        }

        public Criteria andLoginPswdIsNull() {
            addCriterion("login_pswd is null");
            return (Criteria) this;
        }

        public Criteria andLoginPswdIsNotNull() {
            addCriterion("login_pswd is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPswdEqualTo(String value) {
            addCriterion("login_pswd =", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdNotEqualTo(String value) {
            addCriterion("login_pswd <>", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdGreaterThan(String value) {
            addCriterion("login_pswd >", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdGreaterThanOrEqualTo(String value) {
            addCriterion("login_pswd >=", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdLessThan(String value) {
            addCriterion("login_pswd <", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdLessThanOrEqualTo(String value) {
            addCriterion("login_pswd <=", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdLike(String value) {
            addCriterion("login_pswd like", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdNotLike(String value) {
            addCriterion("login_pswd not like", value, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdIn(List<String> values) {
            addCriterion("login_pswd in", values, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdNotIn(List<String> values) {
            addCriterion("login_pswd not in", values, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdBetween(String value1, String value2) {
            addCriterion("login_pswd between", value1, value2, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andLoginPswdNotBetween(String value1, String value2) {
            addCriterion("login_pswd not between", value1, value2, "loginPswd");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNull() {
            addCriterion("merchant_name is null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNotNull() {
            addCriterion("merchant_name is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameEqualTo(String value) {
            addCriterion("merchant_name =", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotEqualTo(String value) {
            addCriterion("merchant_name <>", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThan(String value) {
            addCriterion("merchant_name >", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_name >=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThan(String value) {
            addCriterion("merchant_name <", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThanOrEqualTo(String value) {
            addCriterion("merchant_name <=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLike(String value) {
            addCriterion("merchant_name like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotLike(String value) {
            addCriterion("merchant_name not like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIn(List<String> values) {
            addCriterion("merchant_name in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotIn(List<String> values) {
            addCriterion("merchant_name not in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameBetween(String value1, String value2) {
            addCriterion("merchant_name between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotBetween(String value1, String value2) {
            addCriterion("merchant_name not between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailIsNull() {
            addCriterion("merchant_email is null");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailIsNotNull() {
            addCriterion("merchant_email is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailEqualTo(String value) {
            addCriterion("merchant_email =", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailNotEqualTo(String value) {
            addCriterion("merchant_email <>", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailGreaterThan(String value) {
            addCriterion("merchant_email >", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_email >=", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailLessThan(String value) {
            addCriterion("merchant_email <", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailLessThanOrEqualTo(String value) {
            addCriterion("merchant_email <=", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailLike(String value) {
            addCriterion("merchant_email like", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailNotLike(String value) {
            addCriterion("merchant_email not like", value, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailIn(List<String> values) {
            addCriterion("merchant_email in", values, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailNotIn(List<String> values) {
            addCriterion("merchant_email not in", values, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailBetween(String value1, String value2) {
            addCriterion("merchant_email between", value1, value2, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andMerchantEmailNotBetween(String value1, String value2) {
            addCriterion("merchant_email not between", value1, value2, "merchantEmail");
            return (Criteria) this;
        }

        public Criteria andAccountNumIsNull() {
            addCriterion("account_num is null");
            return (Criteria) this;
        }

        public Criteria andAccountNumIsNotNull() {
            addCriterion("account_num is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNumEqualTo(String value) {
            addCriterion("account_num =", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumNotEqualTo(String value) {
            addCriterion("account_num <>", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumGreaterThan(String value) {
            addCriterion("account_num >", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumGreaterThanOrEqualTo(String value) {
            addCriterion("account_num >=", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumLessThan(String value) {
            addCriterion("account_num <", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumLessThanOrEqualTo(String value) {
            addCriterion("account_num <=", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumLike(String value) {
            addCriterion("account_num like", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumNotLike(String value) {
            addCriterion("account_num not like", value, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumIn(List<String> values) {
            addCriterion("account_num in", values, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumNotIn(List<String> values) {
            addCriterion("account_num not in", values, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumBetween(String value1, String value2) {
            addCriterion("account_num between", value1, value2, "accountNum");
            return (Criteria) this;
        }

        public Criteria andAccountNumNotBetween(String value1, String value2) {
            addCriterion("account_num not between", value1, value2, "accountNum");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusIsNull() {
            addCriterion("merchant_status is null");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusIsNotNull() {
            addCriterion("merchant_status is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusEqualTo(Integer value) {
            addCriterion("merchant_status =", value, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusNotEqualTo(Integer value) {
            addCriterion("merchant_status <>", value, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusGreaterThan(Integer value) {
            addCriterion("merchant_status >", value, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("merchant_status >=", value, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusLessThan(Integer value) {
            addCriterion("merchant_status <", value, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusLessThanOrEqualTo(Integer value) {
            addCriterion("merchant_status <=", value, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusIn(List<Integer> values) {
            addCriterion("merchant_status in", values, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusNotIn(List<Integer> values) {
            addCriterion("merchant_status not in", values, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusBetween(Integer value1, Integer value2) {
            addCriterion("merchant_status between", value1, value2, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andMerchantStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("merchant_status not between", value1, value2, "merchantStatus");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(Integer value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(Integer value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(Integer value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(Integer value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(Integer value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<Integer> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<Integer> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(Integer value1, Integer value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_merchant
     *
     * @mbggenerated do_not_delete_during_merge Tue May 18 09:20:06 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_merchant
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}