package com.sust.swy.print.entity;

import java.util.Date;

public class Merchant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.login_acct
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String loginAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.login_pswd
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String loginPswd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.merchant_name
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String merchantName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.merchant_email
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String merchantEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.account_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String accountNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.merchant_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer merchantStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_merchant.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.id
     *
     * @return the value of t_merchant.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.id
     *
     * @param id the value for t_merchant.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.login_acct
     *
     * @return the value of t_merchant.login_acct
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getLoginAcct() {
        return loginAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.login_acct
     *
     * @param loginAcct the value for t_merchant.login_acct
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setLoginAcct(String loginAcct) {
        this.loginAcct = loginAcct == null ? null : loginAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.login_pswd
     *
     * @return the value of t_merchant.login_pswd
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getLoginPswd() {
        return loginPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.login_pswd
     *
     * @param loginPswd the value for t_merchant.login_pswd
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setLoginPswd(String loginPswd) {
        this.loginPswd = loginPswd == null ? null : loginPswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.merchant_name
     *
     * @return the value of t_merchant.merchant_name
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.merchant_name
     *
     * @param merchantName the value for t_merchant.merchant_name
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.merchant_email
     *
     * @return the value of t_merchant.merchant_email
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getMerchantEmail() {
        return merchantEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.merchant_email
     *
     * @param merchantEmail the value for t_merchant.merchant_email
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMerchantEmail(String merchantEmail) {
        this.merchantEmail = merchantEmail == null ? null : merchantEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.account_num
     *
     * @return the value of t_merchant.account_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getAccountNum() {
        return accountNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.account_num
     *
     * @param accountNum the value for t_merchant.account_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setAccountNum(String accountNum) {
        this.accountNum = accountNum == null ? null : accountNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.merchant_status
     *
     * @return the value of t_merchant.merchant_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getMerchantStatus() {
        return merchantStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.merchant_status
     *
     * @param merchantStatus the value for t_merchant.merchant_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMerchantStatus(Integer merchantStatus) {
        this.merchantStatus = merchantStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.update_time
     *
     * @return the value of t_merchant.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.update_time
     *
     * @param updateTime the value for t_merchant.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_merchant.is_delete
     *
     * @return the value of t_merchant.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_merchant.is_delete
     *
     * @param isDelete the value for t_merchant.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}