package com.sust.swy.print.entity;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.member_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.merchant_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer merchantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.machine_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer machineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.document_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer orderStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_order_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String payOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_amount
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Double orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_remark
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private String orderRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    private Integer isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.member_id
     *
     * @return the value of t_order.member_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.member_id
     *
     * @param memberId the value for t_order.member_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.merchant_id
     *
     * @return the value of t_order.merchant_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.merchant_id
     *
     * @param merchantId the value for t_order.merchant_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.machine_id
     *
     * @return the value of t_order.machine_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.machine_id
     *
     * @param machineId the value for t_order.machine_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.document_id
     *
     * @return the value of t_order.document_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.document_id
     *
     * @param documentId the value for t_order.document_id
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_num
     *
     * @return the value of t_order.order_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_num
     *
     * @param orderNum the value for t_order.order_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_order_num
     *
     * @return the value of t_order.pay_order_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getPayOrderNum() {
        return payOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_order_num
     *
     * @param payOrderNum the value for t_order.pay_order_num
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setPayOrderNum(String payOrderNum) {
        this.payOrderNum = payOrderNum == null ? null : payOrderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_amount
     *
     * @return the value of t_order.order_amount
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Double getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_amount
     *
     * @param orderAmount the value for t_order.order_amount
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_remark
     *
     * @return the value of t_order.order_remark
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public String getOrderRemark() {
        return orderRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_remark
     *
     * @param orderRemark the value for t_order.order_remark
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setOrderRemark(String orderRemark) {
        this.orderRemark = orderRemark == null ? null : orderRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.update_time
     *
     * @return the value of t_order.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.update_time
     *
     * @param updateTime the value for t_order.update_time
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.is_delete
     *
     * @return the value of t_order.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.is_delete
     *
     * @param isDelete the value for t_order.is_delete
     *
     * @mbggenerated Tue May 18 09:20:06 CST 2021
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }
}